version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: bigdata_lab
    environment:
      POSTGRES_DB: pet_sales
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_password
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./исходные данные:/mock_data:ro